voting:
  error_email_address:
    - test@commonhaus.org
  status:
    badge: https://www.commonhaus.org/votes/{{repoName}}/{{number}}.svg
    page: https://www.commonhaus.org/votes/{{repoName}}/{{number}}.html

notice:
  discussion_comment:
    rules:
      - # Send notification for new comments for items labeled with notice
        action: [created]
        label: [notice]
        then: [email_activity]
  issue_comment:
    rules:
      - # Send notification for new comments for items labeled with notice
        action: [created]
        label: [notice]
        then: [email_activity]
  discussion:
    rules:
      - # If a discussion is created in the Announcements or Reviews 
        # category and it already has the notice label, send an email
        category: 
          - Announcements
          - Consensus Building
        action: [created]
        label: [notice]
        then: [email_activity]
      - # If a discussion is created in the Announcements or Reviews 
        # category and it does not have the notice label, add it.
        category: 
          - Announcements
          - Consensus Building
        action: [created, category_changed]
        label: ["!notice"]
        then: [label_notice]
      - # If a discussion has the notice label applied, send an email
        action: [labeled]
        label: [notice]
        then: [email_activity]
  pull_request:
    rules:
      - # If a pull request modifies bylaws or policies
        # apply the notice label
        action:
          - opened
          - edited
          - closed
        paths:
          - bylaws/*
          - policies/*
        then: [label_notice]
      - # If a pull request is labeled with notice, send an email
        action: [labeled]
        label: [notice]
        then: [email_activity]
  actions:
    label_notice: [notice]
    email_activity: 
      address: 
        - test@commonhaus.org
        - automation@commonhaus.org

sponsors:
  sponsors_repo: commonhaus-test/sponsors-test
  sponsorables:
    - commonhaus
