labels: ["notice"]
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Consensus Building items will be forwarded to the website and to the announcements mailing list.
        > 
        > - Title: Keep the title short and sweet. If there is a time constraint, include it.
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Be descriptive but concise; include any timeline constraints.
      placeholder: "We should be more specific about how our records are kept. <description of proposal>"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Concensus mechanism
      description: |
        Describe how you would like readers to interact with this proposal.
      value: |
        Please respond as follows (using )
        - **👍 (:+1:):** if it looks good to you
        - **👀 (:eyes:):** if you're "ok" with it (it may not be your favorite)
        - **👎 (:-1:):** if you think this needs discussion first
    validations:
      required: true
