name: Push Voting activity to commonhaus.github.io

on:
  workflow_dispatch:

  discussion:
  discussion_comment:

  issues:
  issue_comment:

env:
  GH_BOT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GH_BOT_NAME: "GitHub Action"

jobs:
  foundation_votes:
    uses: commonhaus/vote-record-actions/.github/workflows/receive-votes.yml@main
    with:
      repositories: "commonhaus/foundation"
      removeTags: "notice"
      target_dir: "votes/raw"
      markdown_dir: "votes/results"
      index_file: "votes/README.md"
    secrets: inherit

  test_votes:
    uses: commonhaus/vote-record-actions/.github/workflows/receive-votes.yml@main
    with:
      repositories: "commonhaus-test/automation-test"
      vote_comment_bot: "commonhaus-test-bot[bot]"
      removeTags: "notice"
      target_dir: "votes/raw"
      markdown_dir: "votes/results"
      index_file: "votes/README.md"
    secrets: inherit
