name: Push Voting activity to commonhaus.github.io

on:
  discussion_comment:
  issue_comment:
  workflow_dispatch:
    inputs:
      comment_id:
        type: string
        required: true

permissions: {}

jobs:
  update-vote:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
    - name: Bump voting results
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_PUBLISH_PAT }}
        COMMENT_ID: ${{ github.event.comment.node_id }}
        INPUT: ${{ github.event.inputs.message }}
        SENDER: ${{ github.event.sender.login }}
      run: |
        if [[ -z "$COMMENT_ID" ]]; then
          COMMENT_ID=$INPUT
        else if [[ "$SENDER" != "commonhaus-test-bot[bot]" ]]; then
          echo "Comment skipped. Not bot sender"
          exit 0
        fi
        echo '{"comment_id": "${COMMENT_ID}"}' | gh workflow run -R commonhaus/commonhaus.github.io push-votes.yml --json
